"""fixed linking between user and user details

Revision ID: c051c9dae1c1
Revises: 56c5734eb777
Create Date: 2026-01-15 17:50:17.974933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c051c9dae1c1'
down_revision = '56c5734eb777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('planet', sa.String(), nullable=True),
    sa.Column('university_name', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('university_link', sa.String(), nullable=True),
    sa.Column('need', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('company_strength', sa.Integer(), nullable=True),
    sa.Column('company_web_link', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('members', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userDetail')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('userDetail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.NUMERIC(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('zip_code', sa.INTEGER(), nullable=True),
    sa.Column('planet', sa.VARCHAR(), nullable=True),
    sa.Column('university_name', sa.VARCHAR(), nullable=True),
    sa.Column('course', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.VARCHAR(), nullable=True),
    sa.Column('university_link', sa.VARCHAR(), nullable=True),
    sa.Column('need', sa.VARCHAR(), nullable=True),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.Column('company_type', sa.VARCHAR(), nullable=True),
    sa.Column('company_strength', sa.INTEGER(), nullable=True),
    sa.Column('company_web_link', sa.VARCHAR(), nullable=True),
    sa.Column('job_title', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('members', sa.VARCHAR(), nullable=True),
    sa.Column('education', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_details')
    # ### end Alembic commands ###
